<?php

/**
 * @file
 * Implemented hooks for my_project_dev_content.
 */

use Drupal\my_project_dev_content\MigrationPluginAlterer;
use Drupal\my_project_dev_content\ModuleImplementsAlterer;

/**
 * Implements hook_module_implements_alter().
 */
function my_project_dev_content_module_implements_alter(&$implementations, $hook) {
  ModuleImplementsAlterer::alter($implementations, $hook);
}

/**
 * Implements hook_migration_plugins_alter().
 */
function my_project_dev_content_migration_plugins_alter(&$definitions) {
  MigrationPluginAlterer::alterDefinitions($definitions);
}
