tab_manager.settings:
  type: config_object
  label: 'Tab Manager settings'
  mapping:
    tabs:
      type: sequence
      label: 'Tabs'
      sequence:
        type: mapping
        label: 'Tab'
        mapping:
          id: 
            type: string
            label: 'Id'
          title:
            type: label
            label: 'Title'
          weight:
            type: string
            label: 'Weight'
          hidden:
            type: integer
            label: 'Weight'

