_core:
  default_config_hash: IGXEOM4wHQhsKaCjAxgt-leFoP9014Gb7CQ-M2tSe8w
langcode: fr
backend: fillpdf_service
remote_protocol: http
remote_endpoint: fillpdf.io/xmlrpc.php
allowed_schemes:
  - private
template_scheme: public
shell_locale: en_US.UTF-8
fillpdf_service_api_key: CoN7yYeS8a3XTYM3BPyeG5g8ypqJLsu2HotMQRdg2gwTWe8GsLBesACpfm6u4gno
