_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
langcode: fr
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Roboto Condensed&subset=latin#300'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin#300'
  - 'https://www.google.com/webfonts/family?family=Roboto Condensed&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Roboto Mono&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Roboto Mono&subset=latin#600'
  - 'https://www.google.com/webfonts/family?family=Roboto Condensed&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin#900'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#300'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#500'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#600'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#800'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#900'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Gravitas One&subset=latin#regular'
load_on_themes:
  panecom_bstrp: panecom_bstrp
