_core:
  default_config_hash: ySh6lmKUH2SCk5s532zkdNU9PeyNywkaFGVLbWBbRWY
langcode: fr
patterns: "/fr/node-*-programme\r\n/en/node-*-programme\r\n/fr/session/*\r\n/en/session/*\r\n/fr/programme/*\r\n/en/programme/*"
default_width: 700
lightbox_class: lightboxc
skip_admin_paths: true
renderer: drupal_dialog
