<?php

/**
 * @file
 * Replace the type of the email 'message' field from 'textfield' to 'textarea'.
 *
 * See: https://www.drupal.org/project/rules/issues/2724129
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for 'rules_expression_edit' form.
 */
function rules_send_big_email_form_rules_expression_edit_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (!isset($form_state->getStorage()['context_message'])) {
    return;
  }

  // 'Data selection mode' is not worked if the field type is 'textarea'.
  // If a user select 'Data selection mode' then don't change the filed type.
  if ($form_state->getStorage()['context_message'] == 'selector') {
    return;
  }

  // Ensure that we act on a form related with email sending actions.
  $subject = isset($form['context_definitions']['subject']);
  $message = isset($form['context_definitions']['message']['setting']['#type']);
  $reply = isset($form['context_definitions']['reply']);

  if ($subject && $message && $reply) {
    $form['context_definitions']['message']['setting']['#type'] = 'textarea';
  }
}
