<?php

use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implements hook_entity_type_alter().
 * Alterons dynamiquement les urls des terms de taxonomy afin de les faire correspondre aux filtres de recherche
 */
/*function mytools_entity_type_alter(array &$entity_types) {
  // Unset the canonical link template for node content type and
  // replace with a uri callback.
  // Unsetting the uri template is necessary for the uri callbacks to work.
  $entity_types['taxonomy_term']->setUriCallback('mytools_taxonomy_uri');
  $links = $entity_types['taxonomy_term']->get('links');
 // unset($links['canonical']);
  $entity_types['taxonomy_term']->set('links', $links);
}
*/

/**
 * alter paths for the specific agenda taxonomy terms 
 */
/*function mytools_taxonomy_uri($term) {
	if ($term->bundle() == 'date') 
		return Url::fromRoute('view.agenda.page_1', ['field_date_target_id[]' => $term ->id()]);
	elseif ($term->bundle() == 'horaires') 
		return Url::fromRoute('view.agenda.page_1', ['field_horaire_target_id[]' => $term ->id()]);
	elseif ($term->bundle() == 'salle') 
		return Url::fromRoute('view.agenda.page_1', ['field_salle_target_id[]' => $term ->id()]);
	elseif ($term->bundle() == 'legende') 
		return Url::fromRoute('view.agenda.page_1', ['field_legende_target_id[]' => $term ->id()]);
	elseif ($term->bundle() == 'motscles') 
		return Url::fromRoute('view.agenda.page_1', ['field_mot_s_cle_s__target_id[]' => $term ->id()]);
	
	//by default (native)
	return new Url('entity.taxonomy_term.canonical', array(
		'taxonomy_term' => $term ->id(),
	));
}
*/

function mytools_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $view_ids = ['agenda'];
  \Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_agenda");
  if ($form_id == 'views_exposed_form' && in_array($form_state->get('view')->id(), $view_ids)) {

		
    //$form['field_new_used']['#attributes']['disabled'] = 'disabled';
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_agenda_if");
	//$current_langcode = "ju";
	$current_langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_agenda_current_langcode:".$current_langcode);
	$terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
	  'langcode' => $current_langcode
	]);
	$tids = array();
	foreach ($terms as $key => $val)
		$tids[$key] = $key;
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_a:". '<pre><code>' . print_r($terms, TRUE) . '</code></pre>' );
	//\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter:". '<pre><code>' . implode("_", array_keys($terms)) . '</code></pre>' );
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_salle_options:". '<pre><code>' . implode("_", array_keys($form['field_salle_target_id']['#options'])) . '</code></pre>' );
	//var_dump($terms); exit;
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter:". '<pre><code>' . print_r($form['field_salle_target_id']['#options'], TRUE) . '</code></pre>' );
	\Drupal::logger('mytools')->notice("mytools_form_views_exposed_form_alter_b:". '<pre><code>' . print_r($tids, TRUE) . '</code></pre>' );
	$form['field_salle_target_id']['#options'] = array_intersect_key($form['field_salle_target_id']['#options'], $tids);
  }
}

