layout_plugin.settings.lb_tabs:
  type: lb_tabs
layout_plugin.settings.lb_tabs_accordion:
  type: lb_tabs
lb_tabs:
  type: layout_plugin.settings
  mapping:
    initially_active_item:
      type: integer
      label: Initially active item
    collapsible:
      type: boolean
      label: Collapsible
    labels_from_blocks:
      type: boolean
      label: Labels from blocks
